app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }
logout:
    path: /logout
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin