# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, our_db_provider]
        in_memory:
            memory:
                users:
                    admin:
                      password: $2y$13$7W7FXm4hVn7Vg7NvVggaheHYmP5to0nIXiE/0Pb4GY1OXhM0MaMmq
                      roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /post

    access_control:
        - { path: ^/post/new, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
